# Generated by Django 4.1.3 on 2023-03-25 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamepredictor', '0005_alter_games_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_input', models.ManyToManyField(null=True, related_name='previous_input', to='gamepredictor.games')),
                ('reported_games', models.ManyToManyField(null=True, related_name='reported_games', to='gamepredictor.games')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
