# Generated by Django 4.1.3 on 2023-03-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepredictor', '0006_gameuserextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuserextension',
            name='previous_input',
            field=models.ManyToManyField(null=True, related_name='previous_input', related_query_name='previous_input', to='gamepredictor.games'),
        ),
        migrations.AlterField(
            model_name='gameuserextension',
            name='reported_games',
            field=models.ManyToManyField(null=True, related_name='reported_games', related_query_name='reported_games', to='gamepredictor.games'),
        ),
    ]
